name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ] # voert de workflow uit telkens wanneer er een push naar de master-branch gedaan wordt

jobs:

  build:
    runs-on: ubuntu-latest # hier draait het build-proces op, niet de applicatie!

    permissions:
      packages: write # om packages te schrijven naar de ghcr

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # het is mogelijk dat je deze token eerst nog moet aanmaken

    - name: Build the Docker image
      run: docker build -t ghcr.io/rutgersmits/voorbeeld-applicatie:latest . # maak een image aan de hand van de Dockerfile
    
    - name: Push the Docker image
      run: docker push ghcr.io/rutgersmits/voorbeeld-applicatie:latest # publiceer de image naar ghcr